In [1]:
using LinearAlgebra

In [12]:
function LU(A) #A é uma matriz nxn
    n,n=size(A)
    L=zeros(n,n)
    U=zeros(n,n)
    
    for i=1:n
        pivô=A[i,i]
        coluna=(1/pivô)*A[:,i]
        linha=A[i,:]
        A=A-coluna*linha'
        L[:,i]=coluna
        U[i,:]=linha
    end
    return L,U
end

LU (generic function with 1 method)

In [13]:
A=[2 1 2; 10 14 10;14 47 17]

3×3 Matrix{Int64}:
  2   1   2
 10  14  10
 14  47  17

In [15]:
L,U=LU(A)

([1.0 0.0 0.0; 5.0 1.0 0.0; 7.0 4.444444444444445 1.0], [2.0 1.0 2.0; 0.0 9.0 0.0; 0.0 0.0 3.0])

In [16]:
L

3×3 Matrix{Float64}:
 1.0  0.0      0.0
 5.0  1.0      0.0
 7.0  4.44444  1.0

In [17]:
U

3×3 Matrix{Float64}:
 2.0  1.0  2.0
 0.0  9.0  0.0
 0.0  0.0  3.0

In [74]:
#teste
A=randn(100,100)
L,U=LU(A)
norm(A-L*U)<0.00001

true

In [75]:
function normalizar(v)
    return v/norm(v)
end

normalizar (generic function with 1 method)

In [79]:
v=[3;4]
normalizar(v)


2-element Vector{Float64}:
 0.6
 0.8

In [81]:
function QR(A) #A é uma matriz nxn
    n,n=size(A)
    Q=zeros(n,n)
    R=zeros(n,n)
    
    for i=1:n
        coluna=normalizar(A[:,i])
        linha=A'*coluna
        A=A-coluna*linha'
        Q[:,i]=coluna
        R[i,:]=linha
    end
    return Q,R
end

QR (generic function with 1 method)

In [91]:
#teste
A=randn(4,4)
Q,R=QR(A)
norm(A-Q*R)<0.00001

true

In [104]:
reduce_to_zero.(Q*Q')

4×4 Matrix{Real}:
 1.0  0    0    0
 0    1.0  0    0
 0    0    1.0  0
 0    0    0    1.0

In [100]:
function reduce_to_zero(a)
    if abs(a)<0.000001
        return 0
    else 
        return a
    end
end

reduce_to_zero (generic function with 1 method)

In [102]:
reduce_to_zero(0.000000003)

0

In [94]:
A

4×4 Matrix{Float64}:
 -0.577983   0.40422     0.504092   0.590056
 -0.388761  -0.0893016   0.183944   0.209774
 -0.208975  -0.27822     1.45001   -0.114885
  0.697418   0.794468   -0.443932  -0.370594

In [112]:
n=30
A=randn(n,n)
Q,R=QR(A)
reduce_to_zero.(Q*Q')


30×30 Matrix{Real}:
 1.0  0    0    0    0    0    0    0    …  0    0    0    0    0    0    0
 0    1.0  0    0    0    0    0    0       0    0    0    0    0    0    0
 0    0    1.0  0    0    0    0    0       0    0    0    0    0    0    0
 0    0    0    1.0  0    0    0    0       0    0    0    0    0    0    0
 0    0    0    0    1.0  0    0    0       0    0    0    0    0    0    0
 0    0    0    0    0    1.0  0    0    …  0    0    0    0    0    0    0
 0    0    0    0    0    0    1.0  0       0    0    0    0    0    0    0
 0    0    0    0    0    0    0    1.0     0    0    0    0    0    0    0
 0    0    0    0    0    0    0    0       0    0    0    0    0    0    0
 0    0    0    0    0    0    0    0       0    0    0    0    0    0    0
 0    0    0    0    0    0    0    0    …  0    0    0    0    0    0    0
 0    0    0    0    0    0    0    0       0    0    0    0    0    0    0
 0    0    0    0    0    0    0    0       0    0    0    0    0   

In [113]:
norm(A-Q*R)

6.615993618983323e-15

In [136]:
function QR_clássico(A) #A é uma matriz nxn
    n,n=size(A)
    Q=zeros(3,3)
    Q[:,1]=normalizar(A[:,1])
    Q[:,2]=A[:,2]-proj(A[:,2],Q[:,1:1])
    Q[:,2]=normalizar(Q[:,2])
    Q[:,3]=A[:,3]-proj(A[:,3],Q[:,1:2])
    Q[:,3]=normalizar(Q[:,3])
    #CASA generalizar
    return Q
end

QR_clássico (generic function with 1 method)

In [137]:
function proj(a,Q)
    n,m=size(Q)
    P=zeros(n,1)
    for i=1:m
        P=P+(a'*Q[:,i])*Q[:,i]
    end
    return P
end

proj (generic function with 1 method)

In [138]:
Q=randn(3,3)
a=[2;1;3]
proj(a,Q)

3×1 Matrix{Float64}:
 -0.6582921203068806
  3.9406979538947478
  6.297743051802289

In [140]:
n=3
A=randn(n,n)
Q=QR_clássico(A)
reduce_to_zero.(Q'*Q)

3×3 Matrix{Real}:
 1.0  0    0
 0    1.0  0
 0    0    1.0