In [2]:
using LinearAlgebra

In [8]:
A=randn(3,3)

3×3 Matrix{Float64}:
  0.0574904  0.405605  -0.0348101
 -0.678504   0.382553  -0.566191
  0.82302    0.375992   0.0344451

In [9]:
L,U=lu(A)

LU{Float64, Matrix{Float64}}
L factor:
3×3 Matrix{Float64}:
  1.0        0.0       0.0
 -0.824407   1.0       0.0
  0.0698529  0.547766  1.0
U factor:
3×3 Matrix{Float64}:
 0.82302  0.375992   0.0344451
 0.0      0.692524  -0.537794
 0.0      0.0        0.257369

In [6]:
L

3×3 Matrix{Float64}:
  1.0        0.0      0.0
 -0.385235   1.0      0.0
  0.100574  -0.45509  1.0

In [7]:
U

3×3 Matrix{Float64}:
 -2.04324  -0.399829  -1.22269
  0.0      -1.44376   -0.705034
  0.0       0.0        0.638016

In [14]:
function LU(A) #vamos A é quadrada nxn
    n,n=size(A)
    L=zeros(n,n)
    U=zeros(n,n)
    for i=1:n
        pivô=A[i,i]
        linha=A[i,:]
        coluna=(1/pivô)*A[:,i]
        L[:,i]=coluna
        U[i,:]=linha
        A=A-coluna*linha'
    end
    return L,U
end

LU

In [15]:
A=[ 2 1 2;10 14 10;14 47 17]

3×3 Matrix{Int64}:
  2   1   2
 10  14  10
 14  47  17

In [17]:
L,U=LU(A)

([1.0 0.0 0.0; 5.0 1.0 0.0; 7.0 4.444444444444445 1.0], [2.0 1.0 2.0; 0.0 9.0 0.0; 0.0 0.0 3.0])

In [18]:
L

3×3 Matrix{Float64}:
 1.0  0.0      0.0
 5.0  1.0      0.0
 7.0  4.44444  1.0

In [19]:
U

3×3 Matrix{Float64}:
 2.0  1.0  2.0
 0.0  9.0  0.0
 0.0  0.0  3.0

In [21]:
R=randn(3,3)
L,U=LU(R)

([1.0 0.0 0.0; -1.3364483669017542 1.0 0.0; -0.8995923579055798 3.968973167534193 1.0], [1.2128668196468209 1.2555161308728777 -0.2224092048161544; 2.220446049250313e-16 0.2999545083825137 -0.9717816808361869; -8.812890789431799e-16 0.0 4.628733960752417])

In [22]:
L

3×3 Matrix{Float64}:
  1.0       0.0      0.0
 -1.33645   1.0      0.0
 -0.899592  3.96897  1.0

In [23]:
U

3×3 Matrix{Float64}:
  1.21287      1.25552   -0.222409
  2.22045e-16  0.299955  -0.971782
 -8.81289e-16  0.0        4.62873

In [ ]:
R=randn(1000,10000)
L,U=LU(R)
norm(R-L*U)