In [3]:
using LinearAlgebra

In [4]:
A=randn(500,500)
b=randn(500,1)
x=A\b

500×1 Matrix{Float64}:
  1.8082060420387749
 -0.07375951069256581
 -0.5083288888213378
  0.7560683666995749
  0.38058955246834514
 -0.8539978626644211
  0.1424989655924861
  0.5565731524316099
  1.2840006595997453
 -1.411508608469085
 -2.0895656670536917
  0.1177625708569727
  0.41108923718441426
  ⋮
 -0.06330765683427876
 -0.5683248632702776
  1.008153898901281
 -1.371539819373402
 -0.8730047606731882
 -0.09717797630302377
  1.5977218403366285
 -0.7244237574026968
 -0.032452087388707966
  1.363271096816419
  0.20693582432018973
 -0.8516529334661482

In [5]:
tamanho_erro=(1/500)*norm(A*x-b)

4.205964312324627e-15

In [6]:
A=randn(10,3)
b=randn(10,1)
x=A\b

3×1 Matrix{Float64}:
 -0.4459028286654574
  0.351055401698576
 -0.9042939387060374

In [7]:
norm(A*x-b)

2.2508572921205676

In [8]:
v=randn(3,1)

3×1 Matrix{Float64}:
  1.0981074679915177
 -1.140408810329833
  0.4342103040000612

In [9]:
norm(v)

1.6416183643089746

In [10]:
sqrt(v'*v)

1×1 Matrix{Float64}:
 1.6416183643089746

In [11]:
q_1=[1; 2]
q_2=[2;-1]
q_1'*q_2
Q=[q_1 q_2]

2×2 Matrix{Int64}:
 1   2
 2  -1

In [12]:
function normalizar(v)
    return v/norm(v)
end

normalizar (generic function with 1 method)

In [13]:
q_1=normalizar(q_1)
q_2=normalizar(q_2)
Q=[q_1 q_2]

2×2 Matrix{Float64}:
 0.447214   0.894427
 0.894427  -0.447214

In [14]:
Q'*Q

2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0

In [15]:
A=randn(2,2)
Q,R=qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}}
Q factor:
2×2 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}}:
 -0.823561  -0.567227
 -0.567227   0.823561
R factor:
2×2 Matrix{Float64}:
 0.893086  -0.21192
 0.0       -0.198934

In [16]:
Q'*Q

2×2 Matrix{Float64}:
  1.0          -1.11022e-16
 -1.11022e-16   1.0

In [17]:
function QR(a1, a2)
    q1=normalizar(a1)
    p=projetar(a2,q1)
    q2=a2-p
    q2=normalizar(q2)
    return q1,q2
end

QR (generic function with 1 method)

In [18]:
function projetar_em_dois_vetores(b,v,w) #||v||=1, ||w||=1 v perp w , v e w geram um plano
    x=(b'*v) # 
    y=(b'*w) #
    return v*x + w*y
end

projetar_em_dois_vetores (generic function with 1 method)

In [19]:
function projetar_em_um_vetor(b,v) #||v||=1,  v  geram uma reta
    x=(b'*v) # 
    return v*x
end

projetar_em_um_vetor (generic function with 1 method)

In [20]:
#TESTE
direção=randn(2,1)
direção=normalizar(direção)
v=randn(2,1)
projetar(v,direção)
#TESTE:CASA

LoadError: UndefVarError: projetar not defined

In [21]:
#Teste do QR
a1=randn(2,1)
a2=randn(2,1)
q1,q2=QR(a1,a2)
Q=[q1 q2]
Q'*Q

LoadError: UndefVarError: projetar not defined

In [22]:
function QR2(A)
    a1=A[:,1]
    a2=A[:,2]
    
    r11=norm(a1)
    q1=a1/r11
    
    r12=(a2'*q1) #tamanho da projeção do a2 na reta gerada por q1
    p=q1*r12
    q2=a2-p
    
    r22=norm(q2)
    q2=q2/r22
    
    Q=[q1 q2]
    R=[r11 r12; 0 r22]
    
    return Q, R
end

QR2 (generic function with 1 method)

In [23]:
A=randn(2,2)
Q,R=QR2(A)
#Q'*Q
#R
norm(A-Q*R)<0.0000000000001

true

In [32]:
function QR3D(a1, a2, a3)
    q1=normalizar(a1)
    p1= projetar_em_um_vetor(a2,q1)
    q2=a2-p1
    q2=normalizar(q2)
    p2=projetar_em_dois_vetores(a3,q1,q2)
    q3=a3-p2
    q3=normalizar(q3)
    
    return q1,q2,q3
end

QR3D (generic function with 1 method)

In [33]:
#teste
#Teste do QR
a1=randn(3,1)
a2=randn(3,1)
a3=randn(3,1)
q1,q2,q3=QR3D(a1,a2,a3)
Q=[q1 q2 q3]
Q'*Q

3×3 Matrix{Float64}:
 1.0          1.249e-16    1.88738e-15
 1.249e-16    1.0          3.61516e-15
 1.88738e-15  3.61516e-15  1.0

In [41]:
function QR_geral(A)
    n,n=size(A)
    Q=zeros(n,n)
    Q[:,1]=normalizar(A[:,1])
    for i=2:n
        p= projetar_geral(A[:,i],Q[:,1:(i-1)])
        Q[:,i]=A[:,i]-p
        Q[:,i]=normalizar(Q[:,i])
    end
    return Q
end

QR_geral (generic function with 1 method)

In [51]:
A=randn(40,40)
Q=QR_geral(A)
norm(Q'*Q)^2

40.00000000000001

In [38]:
function projetar_geral(b,M)
    m,n=size(M)
    proj=zeros(m,1)
    for i=1:n
        proj+=M[:,i]*(b'*M[:,i])
    end
    return proj
end

projetar_geral (generic function with 1 method)

In [40]:
b=[1;1;1]
M=[ 1 0;
    0 1;
    0 0 ]
projetar_geral(b,M)

3×1 Matrix{Float64}:
 1.0
 1.0
 0.0

In [35]:
A=randn(3,3)
Q=QR_geral(A)
Q'*Q

3×3 Matrix{Float64}:
 1.0          1.66533e-16  3.33067e-16
 1.66533e-16  1.0          8.32667e-17
 3.33067e-16  8.32667e-17  1.0